services:
  nginx:
    image: nginx:1.17-alpine
    ports:
      - "80:80"
    volumes:
      - .:/app
      - ./config_nginx:/etc/nginx/conf.d/default.conf

  phpfpm:
    build:
      context: ./Dockerfiles
      dockerfile: php.Dockerfiles
    environment:
      DB_HOST: ${DB_HOST}
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    volumes:
      - .:/app
      - ./config_php:/usr/local/etc/php/php.ini
      - ./config_xdebug:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini

  postgres:
    image: postgres:13.16
    restart: always
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
    ports:
      - "5432:5432"